version: "3"

services:
  bot: 
    image: alexeymrvz/lobsterbot
    container_name: "lobsterbot"
    command: sh -c "PYTHONPATH='.' python3 bot/bot.py"
    env_file:
      - ./creds/credentials.env
    volumes:
     - ./data:/data
